
development:
  adapter: postgresql
  encoding: unicode
  database: yearbooker_development
  pool: 5
  username: nicholasbundy
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: yearbooker_test
  pool: 5
  username: nicholasbundy


production:
  adapter: postgresql
  encoding: unicode
  database: yearbooker_production
  pool: 5
  username: nicholasbundy
  password:

